# Generated by Django 4.2.7 on 2025-12-11 22:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title of your vlog', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly version of the title (auto-generated)', unique=True)),
                ('video_url', models.URLField(help_text='Enter the URL of your video (YouTube, Vimeo, etc.)', validators=[django.core.validators.URLValidator()])),
                ('description', models.TextField(help_text='Detailed description of your vlog content')),
                ('published_date', models.DateTimeField(help_text='Date when the vlog was published')),
                ('updated_date', models.DateTimeField(auto_now=True, help_text='Automatically updated when the vlog is modified')),
                ('tags', models.CharField(blank=True, help_text='Enter tags separated by commas (e.g., tutorial, beginner, django)', max_length=500)),
                ('thumbnail', models.ImageField(blank=True, help_text='Upload a custom thumbnail image for your vlog', null=True, upload_to='thumbnails/')),
                ('views_count', models.IntegerField(default=0, help_text='Track the number of times this vlog has been viewed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vlogs', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vlogs', to='vlogapp.category')),
            ],
            options={
                'ordering': ['-published_date'],
                'indexes': [models.Index(fields=['-published_date'], name='vlogapp_vlo_publish_292e94_idx'), models.Index(fields=['author'], name='vlogapp_vlo_author__733a5c_idx'), models.Index(fields=['category'], name='vlogapp_vlo_categor_d77202_idx')],
            },
        ),
    ]
